# Generated by Django 5.1.4 on 2025-01-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#FFFFFF', 'White'), ('#FF5733', 'Red'), ('#FF8C00', 'Orange'), ('#FFD700', 'Yellow'), ('#4CAF50', 'Green'), ('#2196F3', 'Blue'), ('#9C27B0', 'Purple'), ('#E91E63', 'Pink'), ('#00BCD4', 'Cyan'), ('#3F51B5', 'Indigo'), ('#FFEB3B', 'Lime')], default='#FFFFFF', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('progress', models.CharField(choices=[('U', 'Unassigned'), ('IP', 'In Progress'), ('S', 'Stuck'), ('C', 'Completed')], default='U', max_length=2)),
                ('tags', models.ManyToManyField(to='main_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
