# Generated by Django 5.1.4 on 2025-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('progress', models.CharField(choices=[('U', 'Unassigned'), ('IP', 'In Progress'), ('S', 'Stuck'), ('C', 'Completed')], default='U', max_length=2)),
            ],
        ),
    ]
