# Generated by Django 5.1.4 on 2025-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('White', '#FFFFFF'), ('Red', '#FF5733'), ('Orange', '#FF8C00'), ('Yellow', '#FFD700'), ('Green', '#4CAF50'), ('Blue', '#2196F3'), ('Purple', '#9C27B0'), ('Pink', '#E91E63'), ('Cyan', '#00BCD4'), ('Indigo', '#3F51B5'), ('Lime', '#FFEB3B')], default='White', max_length=8)),
            ],
        ),
    ]
