# Generated by Django 5.1.4 on 2025-01-17 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1.')]),
        ),
    ]
