# Generated by Django 5.1.4 on 2025-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#FF0000', 'Red'), ('#FF8C00', 'Orange'), ('#FFFF00', 'Yellow'), ('#00FF00', 'Green'), ('#2196F3', 'Blue'), ('#9C27B0', 'Purple'), ('#E91E63', 'Pink'), ('#00BCD4', 'Cyan'), ('#3F51B5', 'Indigo'), ('#32CD32', 'Lime')], default='#FFFFFF', max_length=8),
        ),
    ]
