# Generated by Django 5.1.4 on 2025-01-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#FF5733', 'Red'), ('#FF8C00', 'Orange'), ('#FFD700', 'Yellow'), ('#4CAF50', 'Green'), ('#2196F3', 'Blue'), ('#9C27B0', 'Purple'), ('#E91E63', 'Pink'), ('#00BCD4', 'Cyan'), ('#3F51B5', 'Indigo'), ('#FFEB3B', 'Lime')], default='#FFFFFF', max_length=8),
        ),
    ]
